name: Fake Deploy

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name to deploy'
        type: string
        required: true
      image-tag:
        description: 'Docker image tag to deploy'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Report"
        run: |
          echo "Here I would deploy '${{ inputs.image-name }}:${{ inputs.image-tag }}'"
