name: "3. On Tag"

on:
  push:
    tags:
      - 'build-*'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out ${{ env.GITHUB_REF }}"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{ env.GITHUB_REF }}"
      - name: "Git show"
        run: |
          git show

  push:
    needs: setup
    uses: ./.github/workflows/fake-push.yml
    with:
      image-tag: "${{ github.ref_name }}"

  deploy:
    needs: push
    uses: ./.github/workflows/fake-deploy.yml
    with:
      image-name: "gha-exp"
      image-tag: "${{ github.ref_name }}"
    secrets: inherit
