name: "1. Fake Pass/Fail"

on:
  workflow_dispatch:
    inputs:
      desired_result:
        description: "'pass' or 'fail'"
        default: "pass"
        required: true

jobs:
  pass_fail:
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow status
        run: |
          [[ "${{ github.event.inputs.desired_result }}" == "pass" ]]

  # This doesn't work because *this* workflow hasn't finished, so the status
  # workflow doesn't consider this ref for tagging.
  #
  # maybe_tag:
  #   name: Tag if passed in lieu of scheduled job
  #   needs: pass_fail
  #   uses: ./.github/workflows/status.yml
  #   secrets: inherit
