name: Workflow Status Build Tagger

on:
  workflow_dispatch:
  # Would be on a cron schedule for prod use.

jobs:
  tagger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      # Workflow that must pass for a commit to be buildable.
      WORKFLOW_ID: "118572510"
      # Prefix for YYYYMMDD tags.
      TAG_PREFIX: "build-"

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 50
          fetch-tags: true
          # Must be able to push tags to repo.
          token: ${{ secrets.GH_TOKEN_VARS }}

      - name: Tag most recent passing build on main
        run: |
          set -x
          NEW_TAG="$TAG_PREFIX$(date "+%Y%m%d-%H%M")"

          # Get commit SHA of latest passing workflow.
          passing_sha=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?branch=main&status=success" \
            --jq '.workflow_runs | sort_by(.run_started_at) | last | .head_sha')

          if [[ -z "$passing_sha" ]]; then
            echo "Did not getting a passing build commit SHA"
            exit 128
          fi

          # Tag if untagged.
          echo "Passing commit SHA: $passing_sha"
          if ! git tag --points-at $passing_sha | grep -qe "^$TAG_PREFIX"; then
            echo "Tagging build $NEW_TAG"
            git tag "$NEW_TAG" $passing_sha
            git push origin "$NEW_TAG"
          else
            echo "Build already tagged"
          fi
